### ISSUE TITLE
Multiple editor instances - one server

### ISSUE THREAD

**Issue by alexxbb** [pyQode/pyQode#21]
Hi. First of, thanks for this amazing project, i hope i share one more project using PyQode soon.
I have a problem with multiple editors in my App. When i create new instance of CodeEdit (in QTabWidget) i have to start new instance of backend server, otherwise i get this in consolse:

**DEBUG:pyqode.core.modes.code_completion:retry work request**

Which means **NoRunning** exception raised. 
I use this code to add a new tab

```python
def add_new_tab(self):
    editor = PyQodeWidget() # Basic wrapper on CodeEdit
    editor.exec_selection.connect(self.exec_selected_text)
    editor.dirty_changed.connect(self.pyqode_text_changed)
    self.addTab(editor, "Script_%d" % (len(self.tabs_widgets) + 1))
    self.tabs_widgets.append(editor)
    # If i start backend here, it works fine but it's a very inefficient solution i guess.
    # editor.backend.start(SRV_SCRIPT)
    return editor
```
How to do it right?

Cheers, 
Alexey.

**Comment by ColinDuquesnoy** [comment]
Hi,

Yes, at the moment, the current design requires you to have one server process per editor instance. 

> it works fine but it's a very inefficient solution i guess.

I haven't observed any performace drop with the current solution, even when a dozen of tabs are open (it might be more efficient than what you might think, because those process are spending most of their time sleeping, waiting for a new request).

If you do notice a performance drop we might redesign the system to have one unique server instance.

**Comment by alexxbb** [comment]
Thanks for quick response!
Actually the problem is a little bit deeper :smile: I'm writing a plugin for software which have embedded interpreter, and this software also have a standalone custom interpreter witch require a additional licence to run. So to run backend server, i have to pull one licence for it (which is ok), but having separate server per editor is not possible in my case.
One possible solution is to run server on system interpreter, but this unwanted dependency (on Windows)

**Comment by ColinDuquesnoy** [comment]
I see. To solve your issue, we could add an extra parameter to ``BackendManager.start``(e.g. reuse=False) . The first call would start a new process and cache the port number, any further call would just connect to this server (if reuse is True).

This week I'll be pretty busy with the first public beta release of [MellowPlayer](https://github.com/ColinDuquesnoy/MellowPlayer) but I'll try to look into this issue as soon as I've release the app (maybe during the next weekend). If you're in a hurry you might want to try to fix this yourself and submit a PR :wink:

**Comment by alexxbb** [comment]
Thank you very much! I'll try to fix it if my skills will enough for that. Good luck with MellowPlayer, looks promises :wink:

**Comment by ColinDuquesnoy** [comment]
Implemented in master branch.

I added a ``reuse`` argument to BackendManager.start. Pre-made editors have the ``reuse_backend`` argument in their constructor.

You must always call BackendManager.start and set reuse to true (the backend process will be started on the first call but not on later calls).

Feel free to reopen if that does not work for you (I tested it on linux only).

**Comment by ColinDuquesnoy** [comment]
I've fixed a couple of tricky issues: if you have two editors and close one the backend process should not be stopped. The backend process will only be stopped if no other editors are using it (e.g. you closed all your tabs). At that point if you open a new tab, a new backend process will be started. 

Is it OK for you? (i.e. there will never be two process running at the same time but depending on what the user did, that process might be started and stopped many times during the lifetime of your application).

**Comment by alexxbb** [comment]
Hey Colin, 
I'll try this in weekend, and let you know, thank you  very much.!

**Comment by ColinDuquesnoy** [comment]
> I'll try this in weekend, and let you know, thank you very much.!

Ok, take your time ;) 

All tests are now passing

**Comment by ColinDuquesnoy** [comment]
@alexxbb Any news about this? I'll probably make a new release in a few days but I need to know if this works for you.

**Comment by alexxbb** [comment]
@ColinDuquesnoy Oh, yes, it works fine! Thx Colin!

**Comment by ColinDuquesnoy** [comment]
Great!
