### ISSUE TITLE
No Module Named QtNetwork

### ISSUE THREAD

**Issue by jmwright** [pyQode/pyQode#22]
I have a user who's trying to get cadquery-freecad-module to run on Kubuntu 14.04 64-bit. He gets the error "No Module Named QtNetwork" when he selects the module. I've been able to replicate this error on a Kubuntu 14.04 64-bit VM, trying FreeCAD from the stock repo, stable PPA, and daily PPA. PyQode is the only thing that I see which uses QtNetwork. I'm a little puzzled why this error hasn't shown up before since now the module won't run with any version of FreeCAD that I've tried it on.

The only common denominator that I see is that I tied the module on a fresh install of Kubuntu 14.04.

Any thoughts?

**Comment by ColinDuquesnoy** [comment]
Just a shot in the dark: are you able to successfully import QtNetwork when using a "normal" python interpreter. I remember I onced had issues loading some pyside module because of invalid/missing shared objects.

I tested importing PySide.QtNetwork withing freecad's interpreter on KaOS ((freecad 0.14.3702, PySide 1.2.2) and this worked out of the box (not tested your module):

``` bash
Python 2.7.9 (default, Dec 11 2014, 03:01:43) 
[GCC 4.9.2] on linux2
Type 'help', 'copyright', 'credits' or 'license' for more information.
>>> import WebGui
>>> from StartPage import StartPage
>>> WebGui.openBrowserHTML(StartPage.handle(),'file://' + App.getResourceDir() + 'Mod/Start/StartPage/','Start page')
>>> Gui.activateWorkbench("CadQueryWorkbench")
>>> Gui.activateWorkbench("AssemblyWorkbench")
>>> Gui.activateWorkbench("ArchWorkbench")
>>> Gui.activateWorkbench("CadQueryWorkbench")
>>> from PySide import QtNetwork
>>> QtNetwork.__file__
'/usr/lib/python2.7/site-packages/PySide/QtNetwork.so'
>>> 
```

**Comment by jmwright** [comment]
Ok, so I can import QtGui from PySide in a "normal" Python in Kubuntu 14.04 64-bit, but not QtNetwork. I can however run the following and it works fine.
```python
from PyQt4 import QtNetwork
```
So, it looks like the issue is not with PyQode. Sorry.

**Comment by jmwright** [comment]
I just solved it. For anyone that finds this in the future, run the following line to install the proper missing package.
```
sudo apt-get install python-pyside.qtnetwork
```

**Comment by ColinDuquesnoy** [comment]
Great that you found a solution. Thank you for sharing!
