### ISSUE TITLE
Find Feature

### ISSUE THREAD

**Issue by jmwright** [pyQode/pyQode#23]
Is there a find feature built into the PyQode editor? A quick search of the documentation didn't show one.

**Comment by ColinDuquesnoy** [comment]
Yes, the [SearchAndReplacePanel](https://github.com/pyQode/pyqode.core/blob/master/pyqode/core/panels/search_and_replace.py#L15). (should be in the [preconfigured python editor](https://github.com/pyQode/pyqode.python/blob/master/pyqode/python/widgets/code_edit.py#L73)) 

*Right Click -> Search (or Ctrl+F on almost all platforms)*

**Comment by jmwright** [comment]
Sorry, my tiling window manager seems to be intercepting Ctrl+F.

**Comment by ColinDuquesnoy** [comment]
No problem. ATM, the shortcut is hard-coded and uses ``[QtGui.QKeySequence.Find``. If you need, I could easily add a property to let you change the shortcut. Just let me know.

**Comment by jmwright** [comment]
Ctrl+F is pretty standard. I think I'd rather re-configure my window manager to let that pass through. Thanks for the offer though.
