### ISSUE TITLE
Invalid Syntax on Windows 7 32-bit

### ISSUE THREAD

**Issue by jmwright** [pyQode/pyQode#26]
I've got a user who is having an invalid syntax error that mentions PyQode's autocomplete.py in the stacktrace.

https://github.com/jmwright/cadquery-freecad-module/issues/47

I haven't updated the embedded version of PyQode in this module for awhile. If this is a known issue that's been fixed, I'll try updating.

**Comment by ColinDuquesnoy** [comment]
The issue is that Python 2.6 is not supported. I don't plan to support it. Feel free to submit a PR if you think you can fix that. Or ask the user to upgrade its python.

**Comment by jmwright** [comment]
Ok, thanks.
