### ISSUE TITLE
Editor Autocomplete Confuses Parenthesis and Sqaure Bracket Characters

### ISSUE THREAD

**Issue by jmwright** [pyQode/pyQode#28]
When I have a situation like the following and try to add the closing square bracket, autocomplete will keep trying to convert it to a close parenthesis.
```python
plate = cq.Workplane('XY').pushPoints([(0.0, 0.0), (0.0, 3.0), (3.0, 0.0))
```
I have to end up cutting and pasting a square bracket in to get it to work.

**Comment by ColinDuquesnoy** [comment]
I cannot reproduce your issue with the latest commit on master branch. Which version are you using? I believe I've fixed that issue a couple of version ago (latest is 2.5.0.dev0)

**Comment by jmwright** [comment]
Versions:
pycode.core = 2.5.dev1
pyqode.python = 2.4.dev

Has this problem been fixed since those versions?

Thanks.

**Comment by ColinDuquesnoy** [comment]
Yep issue fixed with [this commit](https://github.com/pyQode/pyqode.core/commit/5d7e955b31be365f405ad4209bf42ca8aa54cdf8#diff-d3994f695b1a8c8c22645214a0207d8a)

**Comment by jmwright** [comment]
Great, I'll update then. Thanks.

**Comment by ColinDuquesnoy** [comment]
If you also update pyqode python to the latest commit on master branch, 
you will notice that some dependencies have changed. pyqode.python no 
longer depends on frosted (and pies) but on pyflakes.

**Comment by jmwright** [comment]
That's good to know, thanks. I would have been confused.

**Comment by jmwright** [comment]
Just to finish this thread off with a definite resolution, I can confirm that the problem is fixed after updating to the latest commit.
