### ISSUE TITLE
Add default behavior for cmd+x without selecting text

### ISSUE THREAD

**Issue by max107** [pyQode/pyQode#29]
If text not selected cut while line.

Sry, my english so bad)

**Comment by ColinDuquesnoy** [comment]
This is the default behaviour of QPlainTextEdit::cut but it should be fairly easy to override. Going to look into this during the weekend.

**Comment by ColinDuquesnoy** [comment]
I've spoken too fast. I forgot that QPlainTextEdit::cut is a slot and a slot cannot be overridden (the c++ implementation is always the one that get executed, my overriden method only get called when you use the context menu). So I'm afraid this is impossible to implement in python. If you care about this feature you should probably submit a feature request to the Qt team.

**Comment by max107** [comment]
@ColinDuquesnoy if this not available via python, then its possible via c++, right? Open issue pls

**Comment by max107** [comment]
hm.. this feature available via override eventFilter.

**Comment by ColinDuquesnoy** [comment]
Well this would require to patch the c++ implementation of *QPlainTextEdit::cut* (you cannot override a slot, even in c++).

During the last night, I had another idea which I haven't tried yet: maybe using an event filter would work.

**Comment by ColinDuquesnoy** [comment]
> hm.. this feature available via override eventFilter.

You're right, this might work. I'll give it a try.

**Comment by ColinDuquesnoy** [comment]
Done. I did the same for copy.

**Comment by max107** [comment]
Thanks!

**Comment by max107** [comment]
For cmd+x need cut whole line and remove empty line.

**Comment by ColinDuquesnoy** [comment]
> and remove empty line.

Good point! At the moment cmd+x cuts the whole line but does nothing if the line is empty. I'll fix that this evening...

**Comment by ColinDuquesnoy** [comment]
Done (but made the wrong link with issue in commit).

**Comment by ColinDuquesnoy** [comment]
The other strange behaviour are now fixed (at least they should, it was a bit more complicated then I initally though)
