### ISSUE TITLE
[Core] Column selection+editing

### ISSUE THREAD

**Issue by ColinDuquesnoy** [pyQode/pyQode#3]
This feature request come from OpenCobolIDE/OpenCobolIDE#9.

This won't be implemented until support for multiple cursor has been implemented( #96 ). Column selection should be a specific case of multiple cursor editing.

@ogranada same question as for #2, do you still want to take care of this feature?

**Comment by GitMensch** [comment]
I'd like to vote for column selection :-)
Column editing (tracked in #2) is another issue that seems to be more complicated.

**Comment by ColinDuquesnoy** [comment]
My wording was misleading. This issue is about *column* selection+editing while issue #2 is about *multiple* selection+editing (similar to what is done with a search and replace operation except that you would choose the selections yourself). Column selection is a specific case of multiple selection.

Column/Block selection is not possible using the QPlainText API, I can only select a single range of characters spanning multiple lines without interruption. To support real column selection I need to add my own selection system using a mix of [ExtraSelection](http://doc.qt.io/qt-5/qtextedit-extraselection.html) (which are used only to apply a selection background) and multiple [QTextCursor](http://doc.qt.io/qt-5/qtextcursor.html) to manipulate the text (copy, delete, edit). Once this system has been setup I will have to setup the "shortcuts" for both #2 and #3 and, at that point, #3 seems indeed simpler.
