### ISSUE TITLE
[Core] Multiline tabs

### ISSUE THREAD

**Issue by max107** [pyQode/pyQode#35]
Not possible work if i can't read tab name :)

![screen shot 2015-04-27 at 14 19 39](https://cloud.githubusercontent.com/assets/862272/7346579/868a2d88-ece8-11e4-97af-a21d2debcbc5.png)

**Comment by ColinDuquesnoy** [comment]
There should be some scroll buttons when there are too many tabs (this is what I have on Linux). I see that this property is style dependant (it might not be enabled on OSX). I'll check that.

AFAIK multiline tabs are not possible with Qt (unless you override the whole rendering of tabs which I'd like to avoid if possible).

**Comment by max107** [comment]
That very bad, because tabs like sublime text is very unuseful if work with big project.

**Comment by ColinDuquesnoy** [comment]
I mean you should have something like that:

![notepad_001](https://cloud.githubusercontent.com/assets/1681217/7347050/cd1c91e0-ece4-11e4-9fec-0004df42a9f0.png)

Is that the same as sublime text?

**Comment by max107** [comment]
Yea, close.

![screen shot 2015-04-27 at 14 55 55](https://cloud.githubusercontent.com/assets/862272/7347084/8a522cae-eced-11e4-82f2-22a9804a7b2c.png)

But this tabs absolutely useless if project bigger than 2-4 files :)

Perfect solution something like this:

![screen shot 2015-04-27 at 14 57 38](https://cloud.githubusercontent.com/assets/862272/7347113/c5b9d012-eced-11e4-857c-902e9c49edef.png)

**Comment by max107** [comment]
Need trying to find solution with qt and multi row tabs.

**Comment by ColinDuquesnoy** [comment]
Maybe you should upvote this feature request: 
https://bugreports.qt.io/browse/QTBUG-2061

Otherwise this means rewriting the entire tab widget (QStackedWidget + 
multiple QTabBar).

I am fine with the scroll buttons since I never keep as much tabs open.

I am not going to implement this myself but will leave the issue open 
in case someone come with a solution.

**Comment by ColinDuquesnoy** [comment]
So the alternative has been implemented. Should we close this issue or keep it open in case Qt implement multi row tabs?

**Comment by max107** [comment]
Keep open. Maybe someone implement this feature.
