### ISSUE TITLE
Another solution for replace multiline tabs

### ISSUE THREAD

**Issue by max107** [pyQode/pyQode#36]
[Rewrite Qt tab widget](https://github.com/pyQode/pyQode/issues/35) is a very long and hard issue. 

As example we can use something like this as temporary solution for improve user interface and make editor more comfortable:

![screen shot 2015-04-27 at 15 39 45](https://cloud.githubusercontent.com/assets/862272/7347684/aa57cbd4-ecf3-11e4-83af-57ddc1c77f58.png)

Idea: by hotkey open popup with currently opened files and navigate via `up`, `down`, `enter` keys.

**Comment by max107** [comment]
@ColinDuquesnoy what do you think about this?

**Comment by ColinDuquesnoy** [comment]
Yes that is a good idea. Now the question is which hotkey should we use by default? ofc we should add a property to change this hotkey but it would be nice to have a default that works well on most platforms.

**Comment by max107** [comment]
cmd+e if unused

**Comment by ColinDuquesnoy** [comment]
cmd+e should work everywhere, alt+o (o for open) would also work

**Comment by ColinDuquesnoy** [comment]
Implemented, default shortcut is cmd+t. Here is how it looks:

![notepad_001](https://cloud.githubusercontent.com/assets/1681217/7355598/3486a88c-ed23-11e4-90f4-4ac881568c6f.png)

**Comment by max107** [comment]
Thanks.
