### ISSUE TITLE
[COBOL] Improve/Rewrite cobol names parser

### ISSUE THREAD

**Issue by ColinDuquesnoy** [pyQode/pyQode#41]
- support statements that span over multiple lines (see OpenCobolIDE/OpenCobolIDE#133)
- change the approach in order to be able to compute the size of a group (see  OpenCobolIDE/OpenCobolIDE#134)
- have subtype for pic fields in order to store the level, type and size (in order to simplify computations), I might be able to get rid of the pic parser from https://github.com/balloob/Python-COBOL

**Comment by GitMensch** [comment]
What is the rough schedule for 2.7 milestone?

**Comment by ColinDuquesnoy** [comment]
I plan to release pyqode 2.7 along with the first alpha version of the new IDE I am working on and OpenCobolIDE 4.7 at the same time. Roughly, this should come during the summer (I hope it will be ready by the end of july). Keep in mind that I am working on this only during my freetime so I don't put any strict deadlines, i.e. it will be available when it is ready.

**Comment by GitMensch** [comment]
Another side point: the column 7 should not be part of the name in paragraphs:

```cobol
      DDATA DIVISION.
      DWORKING-STORAGE SECTION.
```

currently leads to a name ```DDATA DIVISION```.
And while

```cobol
          DATA DIVISION.
          WORKING-STORAGE SECTION.
```

leads to the correct result ```DATA DIVISION``` the source

```cobol
      D   DATA DIVISION.
      D   WORKING-STORAGE SECTION.
```

leads to entries ```D DATA``` and ```D   WORKING-STORAGE SECTION``` (the last one having 3 spaces between D and W)

**Comment by GitMensch** [comment]
Additional to show the type in the tooltip the value (or at least the start of it [as it could be 3000+ bytes) would be useful. Currently it doesn't seem that lvl 78 is supported.

Sample for both:

```cobol

       78  txt-lower          value 'abcdefghijklmnopqrstuvwxyzäöü'.
       78  txt-upper          value 'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ'.
      *
       01  var-a.
           05  filler     pic x(10).
               88  var-a-1-a     value '1.Here'.
               88  var-a-1-b     value '1.There'.
           05  filler     pic x(09).
           05  filler     pic x(09).
           05  filler     pic x(09).
           05  filler     pic x(06).
           05  filler     pic x(10).
           05  filler     pic x(06).
           05  filler     pic x(06).
           05  filler     pic x(05).
           05  filler     pic x(08).
               88  var-a-10-a    value '10.fish'.
               88  var-a-10-b    value '10.sheep'.
               88  var-a-10-no   value spaces.
      *
       78  myexp-1                     value 'save record and go back to
      -                                      ' the main menu'.
       78  myconst-1                   value 'Main'.
       78  myconst-2                   value 'Cancel'.
```

**Comment by ColinDuquesnoy** [comment]
This is quite a big task and will be delayed to pyqode 2.8 (i.e. after the first alpha release of HackEdit)

**Comment by ColinDuquesnoy** [comment]
The pic parser currently does not support the following syntax:

```
01  Buffer-Len                  USAGE BINARY-LONG.
```

**Comment by GitMensch** [comment]
Just for reference: GC2 supports the following usages without PIC

BINARY-CHAR, BINARY-SHORT, BINARY-LONG, BINARY-DOUBLE, BINARY-C-LONG, FLOAT-BINARY-32, FLOAT-DECIMAL-7, FLOAT-BINARY-64, FLOAT-DECIMAL-16, FLOAT-BINARY-128, FLOAT-DECIMAL-34, FLOAT-EXTENDED, POINTER, PROGRAM-POINTER

**Comment by GitMensch** [comment]
Much better!

One thing that I *think* worked before and does not: level 77.
New test.cpy:

~~~~cobol
       77  txt-var01          pic x(20).
      *
       78  txt-lower          value 'abcdefghijklmnopqrstuvwxyzäöü'.
       78  txt-upper          value 'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ'.
      *
       01  var-a.
           05  filler     pic x(10).
               88  var-a-1-a     value '1.Here'.
               88  var-a-1-b     value '1.There'.
           05  filler     pic x(09).
           05  filler     pic x(09).
           05  filler     pic x(09).
           05  filler     pic x(06).
           05  filler     pic x(10).
           05  filler     pic x(06).
           05  filler     pic x(06).
           05  filler     pic x(05).
           05  filler     pic x(08).
               88  var-a-10-a    value '10.fish'.
               88  var-a-10-b    value '10.sheep'.
               88  var-a-10-no   value spaces.
      *
       77  txt-var02          pic 9(10)x(20)
                 .
      *
       78  myexp-1                     value 'save record and go back to
      -                                      ' the main menu'.
       78  myconst-1                   value 'Main'.
       78  myconst-2                   value 'Cancel'.
      *
       77  txt-var03          pic x(20)9(10).
~~~~

**Comment by ColinDuquesnoy** [comment]
> One thing that I think worked before and does not: level 77.

I don't think this was working before, same issue as for level 78. Should be easy to fix.

**Comment by GitMensch** [comment]
Another thing which I've recognized too late (with OCIDE 4.7.3 release): The navigation pane shows all `exit section` as own sections. You can blacklist all reserved words in the names but I think "exit [section]" is enough (both as paragraph and a s section name).

Another approach would be the "correct" recognizing of sections: After `section` you need a period (but you may have [mutliple] empty and/or comment lines and/or the optional [and obsolete] segmentation numbers (numeric literals) before the period. And you need a period before (again: with possibly multiple empty/comment lines).

**Comment by GitMensch** [comment]
Something not as important as the exit section issue but maybe interesting:

~~~~cobol
      *    MSG structure (aligned for x64)
       01  msg.
      *    typedef struct tagMSG {
      *      HWND   hwnd;
      *      UINT   message;
      *      WPARAM wParam;
      *      LPARAM lParam;
      *      DWORD  time;
      *      POINT  pt;
      *    } MSG, *PMSG, *LPMSG;
4/8        03 msg-hwnd                POINTER.                *> HWND
4          03 msg-message             BINARY-LONG UNSIGNED.   *> UINT
       >>IF P64 SET
      * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN *
0/4        03                         PIC X(4).
      * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN *
0/8        03 msg-wParam              BINARY-DOUBLE UNSIGNED. *> WPARAM(x64)
0/8        03 msg-lParam              BINARY-DOUBLE UNSIGNED. *> LPARAM(x64)
       >>ELSE
4/0        03 msg-wParam              BINARY-LONG UNSIGNED.   *> WPARAM(x86)
4/0        03 msg-lParam              BINARY-LONG UNSIGNED.   *> LPARAM(x86)
       >>END-IF
4          03 msg-time                BINARY-LONG UNSIGNED.   *> DWORD
      *    =============================================================
           03 msg-pt.                                         *> POINT structure
      *    typedef struct tagPOINT {
      *      LONG x;
      *      LONG y;
      *    } POINT, *PPOINT;
4             05 msg-pt-x             BINARY-LONG.            *> LONG
4             05 msg-pt-y             BINARY-LONG.            *> LONG
      *    =============================================================
       >>IF P64 SET
      * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN *
0/4        03                         PIC X(4).
      * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN * ALIGN *
       >>END-IF
TOTAL *
28/48 *
~~~~

Nicely shows `FILLER` without the optional keyword (which is handled by the current parser perfectly!) and conditional compilation (which obviously is ignored).
Should I add a feature request for conditional preparsing? You could set preparser options (normally additional command line options `-Dsomething`, in this case P64 as internal define [depending on "64bit-mode" from `cobc -info`]) via GUI and parse that way (in OCIDE "global" in HE on project/file basis).

**Comment by ColinDuquesnoy** [comment]
I didn't know about conditional compilation with GnuCOBOL. I'll check that when I'll write the new parser. The end-section issue should be fixed in the next release of OCIDE.
