### ISSUE TITLE
Missing freeze setup files for pyqode.python examples

### ISSUE THREAD

**Issue by rasteron** [pyQode/pyQode#46]
Hi,

I was trying to build the python freeze examples, particularly pynotepad, but checking the directory here:

https://github.com/pyQode/pyqode.python/tree/master/examples/pynotepad

..there's an instruction for freeze setup but the freeze_setup.py file is missing.

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting. It is indeed missing and I realized the application is not ready for freeze.

I'll have a look ASAP.

**Comment by rasteron** [comment]
Great thanks. PyQode is a great widget! :+1:

**Comment by ColinDuquesnoy** [comment]
I added a freeze setup script and adapted the application to work in a frozen environment. It will use server.exe for the backend if not interpreter has been set. If an external interpreter is in use, it will use server.py (next to executable) and add library.zip to the backend sys.path so that you don't have to install in the target interpreter.

Tested on windows only, might neeed a few tweaks to work on OSX.

**Comment by rasteron** [comment]
Thanks, but when I try for python `freeze_setup.py build`, I get this error

`TypeError: unbound method __init__() must be called with Distribution instance as first argument (got Distribution instance instead)`

that is similar to this one: http://stackoverflow.com/questions/24269117/including-dependencies-in-cx-freeze-setup-py-file

I'm using Python 2.7

**Comment by ColinDuquesnoy** [comment]
I tested it with python 3.4 and PyQt5. Will have a look with python2 tomorrow or later during the week.

Which os?

**Comment by rasteron** [comment]
PySide, Windows 7 x64. Ok thanks Colin! :smile:

**Comment by ColinDuquesnoy** [comment]
You can also experiment by yourself :wink: I would start by removing the inclusing of pygment_styles (those are setuptools plugins). Also maybe try to see if you're using the latest version of setuptools and cx_freeze...

Also keep in mind that there are other alternatives to cx_freeze. At work, I am now using a method inspired by this [blog post](http://cyrille.rossant.net/create-a-standalone-windows-installer-for-your-python-application) I bundle a small standalone launcher frozen using cx_freeze that changes sys.path and sys.executable to point at a portable python installation that sits next to the launcher executable, with all my packages already setup. This is especially nice if you're also using setuptools entry points for you plugin system but might be too much for a small application.

**Comment by rasteron** [comment]
Ok sure thing. Yes, so far my setuptools and cxfreeze are up-to-date. I'm used to PyInstaller but I'll try it out when I can. :smile:

**Comment by ColinDuquesnoy** [comment]
I added a freeze script that works for me on python 2.7.10 and PySide in commit pyQode/pyqode.python@5ba916fa0aec7bc54014d4bf321ab6b1e89b10a4.

For reference here are the version I used to test this script:

```
C:\Windows\SysWOW64>c:\Python27\Scripts\pip.exe list
cx-Freeze (4.3.4)
docutils (0.12)
future (0.14.3)
jedi (0.9.0)
pep8 (1.6.2)
pip (7.0.3)
pyflakes (0.9.0)
Pygments (2.0.2)
pyqode.core (2.6.5)
pyqode.python (2.6.2)
pyqode.qt (2.6.0)
PySide (1.2.2)
pywin32 (219)
setuptools (17.1)
```

**Comment by rasteron** [comment]
Working great now. Thanks! :+1:
