### ISSUE TITLE
Setting default style in Editor

### ISSUE THREAD

**Issue by rasteron** [pyQode/pyQode#47]
Hi,

I know this is more likely of a question rather than an issue, but I'm trying to set a default style to the editor, which is currently set to 'qt'. How do I do this? 

Thanks!

**Comment by ColinDuquesnoy** [comment]
Hi,

No problem with questions, pyqode does not have a forum or a mailing list so it's perfectly fine to use issues for questions.

You need to use the [color_scheme](http://pythonhosted.org/pyqode.core/pyqode.core.api.html#pyqode.core.api.SyntaxHighlighter.color_scheme) property of the syntax highlighter mode.

This should work on any editor that have a syntax highlighter mode:

``` python
from pyqode.core.api import ColorScheme
editor.syntax_highlighter.color_scheme = ColorScheme('monokai')
# with the latest master version of pyqode.core, you can also write it that way
editor.syntax_highlighter.color_scheme = 'monokai'
```

If you're using PyCodeEdit, you can pass the color scheme when you create the widget:

``` python
editor = PyCodeEdit(color_scheme='monokai')
```

If you're using the SplittableCodeEditTabWidget, you can pass a color_scheme argument to the open_document/create_document methods:

``` python
tab_widget.open_document('/path/file.py', color_scheme='monokai')
```

**Comment by rasteron** [comment]
Thanks, got it now. works great!
