### ISSUE TITLE
[Core] Add a read-only panel that indicates when a file is read-only

### ISSUE THREAD

**Issue by ColinDuquesnoy** [pyQode/pyQode#50]
The file manager should detect whether a file is read only, in that case it should add a top panel which indicates the the user cannot make change. It would be a good idea to set the widget's readOnly property to True to prevent the user from working in a file that he cannot save.

**Comment by GitMensch** [comment]
Sounds good. I suggest to add the hint "Use save-as to be able to edit the file." in the top panel.

**Comment by ColinDuquesnoy** [comment]
Implemented in pyqode.core@dev. Here is how it looks:

![screenshot_20151001_191851](https://cloud.githubusercontent.com/assets/1681217/10228103/5ff9cde0-6871-11e5-8940-3e9356f5133e.png)

**Comment by GitMensch** [comment]
Looks good.

**Comment by max107** [comment]
Cool

**Comment by ColinDuquesnoy** [comment]
Glad to see you like it :) I made a few more improvements: now the file watcher will also watch for file permission changes and will toggle the read-only panel/flag as soon as you change the permissions.

@max107 This is a screenshot taken from [HackEdit](https://github.com/HackEdit/hackedit), a new project of mine that I will open source in a few weeks.
