### ISSUE TITLE
[Core] accept existing QSettings object?

### ISSUE THREAD

**Issue by ewerybody** [pyQode/pyQode#55]
Currently in [core.widgets.menu_recents](https://github.com/pyQode/pyqode.core/blob/master/pyqode/core/widgets/menu_recents.py), [core.cache](https://github.com/pyQode/pyqode.core/blob/master/pyqode/core/cache.py) and [core.widgets.splittable_tab_widget](https://github.com/pyQode/pyqode.core/blob/master/pyqode/core/widgets/splittable_tab_widget.py) there are new QSettings objects created.
But it's quite probable that one has created such a settings object already with the main application, might also be one that writes to an INI.
I'd suggest to enable the classes to use a passed QSettings object as well, next to the options in place.

**Comment by ColinDuquesnoy** [comment]
Sounds like a good idea. I am very busy with other projects atm... Care to submit a PR?

**Comment by ewerybody** [comment]
Yea can do. But probably not before next week! :]
Cheers!

**Comment by ColinDuquesnoy** [comment]
Great! No problem, take your time ;)

**Comment by ColinDuquesnoy** [comment]
Implemented in commit pyQode/pyqode.core@d00db3c49ce75d93c9e2b81ff70e055da33e54ba. Let me know if that works for you.

**Comment by ewerybody** [comment]
Ahh cool! I'll try it out! ..
