### ISSUE TITLE
Question: How to add  pyQode to an existing PyQT app?

### ISSUE THREAD

**Issue by GitMensch** [pyQode/pyQode#57]
We use a small python app for internal use. The main widget shows loaded COBOL sources (kind of a compiling list for display only), currently in a text widget.

Questions:
- How can pyQode be used in this app?
- I "guess" with the cobol module syntax highlighting comes on the fly - what about a navigation pane similar to OCIDE?

I'd be lucky if we could actually "see" much as much COBOL as possible in the current text widget, but I don't know what effort has to be done. Hints appreciated.

Simon

**Comment by ColinDuquesnoy** [comment]
This [basic example](https://github.com/pyQode/pyqode.cobol/blob/master/examples/cobedit.py) should get you started. It creates a main window with the cobol editor as the central widget and adds two dock widgets: one for displaying the editor's outline (i.e. the navigation pane) and one for the offset calculator.

You'll also get more information about how to use pyqode by reading the [wiki](https://github.com/pyQode/pyQode/wiki) and the [API references of pyqode.core](http://pythonhosted.org/pyqode.core).

Let me know if you have any other questions.
