### ISSUE TITLE
Python2 Syntax error

### ISSUE THREAD

**Issue by TimBritton** [pyQode/pyQode#58]
Hi,
There is a syntax error on line 1256 in pyqode.core.widgets.splittable_tab_widget.py involving the differences between py2 and py3 file IO.  
`
 with open(path, encoding=encoding) as f:
`

The open function does not contain the encoding parameter in python 2.

This code is accessed whenever save_current() and save_all() is called.

**Comment by TimBritton** [comment]
I have created a pull request with the fix I have implemented. See pull request #159

**Comment by ColinDuquesnoy** [comment]
Thank you! I merged your PR and I will release a new version on pypi in a few days.

**Comment by GitMensch** [comment]
Why is this issue is still open if everything is in the PR and it is merged and released?

**Comment by ColinDuquesnoy** [comment]
I thought I would close it once pyqode 2.10 has been released, which is now done.
