### ISSUE TITLE
pyqode inside SideFX Houdini

### ISSUE THREAD

**Issue by paulwinex** [pyQode/pyQode#59]
Hi, i want to use pyqode editor inside Houdini application. Houdini have embedded Python 2.7.5. When i try to start test pyqode widget i have error:
_TypeError: 'module' object is not callable_
What is mean? I cant use pyqode on Python 2.7.5? With 2.7.11 works ok.

**Comment by ColinDuquesnoy** [comment]
Hello,

It's hard to say without seing the **complete traceback** and your **code**. 

Generally speaking, you should be able to use pyqode on any Python 2.7, it is currently being [tested with Python 2.7.6](https://travis-ci.org/pyQode/pyqode.core/jobs/135241901#L157).

I'll need more information to be able to help you.

**Comment by paulwinex** [comment]
I just copy pyqode to different folder and add path ty sys.path for Houdini.
Next i use this code https://gist.github.com/paulwinex/0b1f08e98cab1b19c319c75001509ea6
And catch this error
```
Python 2.7.5 (default, Oct 15 2015, 15:22:58) [MSC v.1900 64 bit (AMD64)] on win32
Houdini 15.5.480 hou module imported.
>>> import sys
>>> sys.path.append('D:/work/vex/pyqd_tst')
>>> import pqeditor
>>> pqeditor.show()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:/work/vex/pyqd_tst\pqeditor.py", line 37, in show
    editor.file.open(__file__)
  File "D:/work/vex/pyqd_tst\pyqode\core\managers\file.py", line 234, in open
    path, preferred_encoding=encoding)
  File "D:/work/vex/pyqd_tst\pyqode\core\cache.py", line 96, in get_file_encoding
    with open(file_path, encoding=encoding) as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```
I removed this keyword and try again
```
>>> reload(pqeditor)
<module 'pqeditor' from 'D:/work/vex/pyqd_tst\pqeditor.py'>
>>> pqeditor.show()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:/work/vex/pyqd_tst\pqeditor.py", line 18, in show
    editor = api.CodeEdit()
  File "D:/work/vex/pyqd_tst\pyqode\core\api\code_edit.py", line 486, in __init__
    self._init_actions(create_default_actions)
  File "D:/work/vex/pyqd_tst\pyqode\core\api\code_edit.py", line 1132, in _init_actions
    menu_advanced = QtWidgets.QMenu(_('Advanced'))
TypeError: 'module' object is not callable
>>> 
```
And this error repeats always.

**Comment by ColinDuquesnoy** [comment]
> TypeError: 'encoding' is an invalid keyword argument for this function

Do you have [future](https://pypi.python.org/pypi/future) installed in your python 2 environment?

> menu_advanced = QtWidgets.QMenu(_('Advanced'))

Can you add the following print statement before this line?

```python
print(QtWidgets.QMenu, _)
```

``QtWidgets.QMenu`` should be either ``PyQt4.QtGui.QMenu`` or ``PySide.QtGui.QMenu`` or ``PyQt5.QtWidgets.QMenu`` depending on the toolkit you're using. ``_``should be a gettext.NullTranslation set [here](https://github.com/pyQode/pyqode.core/blob/master/pyqode/core/__init__.py#L21).

**Comment by paulwinex** [comment]
> Do you have future installed in your python 2 environment?

This import works without errors

`from __future__ import absolute_import, division,  print_function, unicode_literals`

> print(QtWidgets.QMenu, _)
Result:
```
<type 'PySide.QtGui.QMenu'> <bound method NullTranslations.gettext of <gettext.NullTranslati
ons instance at 0x000000004EAB5B88>>
```

**Comment by paulwinex** [comment]
PySide.__version__ 
'1.2.2'

**Comment by ColinDuquesnoy** [comment]
> This import works without errors
from __future__ import absolute_import, division, print_function, unicode_literals

Does the following import work? 

``from future.builtins import open``

> ``<type 'PySide.QtGui.QMenu'> <bound method NullTranslations.gettext of <gettext.NullTranslati
ons instance at 0x000000004EAB5B88>>``

Strange, everything looks good. What if you replace QtWidgets.QMenu(_('Advanced')) with QtWidgets.QMenu('Advanced')?

**Comment by paulwinex** [comment]
```
>>> from future.builtins import open
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named future.builtins
```
Not supported(((

> What if you replace QtWidgets.QMenu(_('Advanced')) with QtWidgets.QMenu('Advanced')?

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:/work/vex/pyqd_tst\pqeditor.py", line 18, in show
    editor = api.CodeEdit()
  File "D:/work/vex/pyqd_tst\pyqode\core\api\code_edit.py", line 486, in __init__
    self._init_actions(create_default_actions)
  File "D:/work/vex/pyqd_tst\pyqode\core\api\code_edit.py", line 1133, in _init_actions
    menu_advanced = QtWidgets.QMenu('Advanced')
TypeError: 'module' object is not callable
```
Strange error

**Comment by ColinDuquesnoy** [comment]
> Not supported(((

Download [future](https://pypi.python.org/pypi/future) and add its path to sys.path, that should work.

> Strange error

Can you make sure the following works:

```
from PySide import QtGui
m = QtGui.QMenu('Menu')
```

**Comment by paulwinex** [comment]
> from PySide import QtGui
> m = QtGui.QMenu('Menu')

Yes, it works. I want to use pyqode for new version of [VEX Editor](https://github.com/paulwinex/pw_Houdini_VEX_Editor) and i checked all Qt widgets.

After install future for Houdini interpreter i have this

```
>>> import pqeditor
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:/work/vex/pyqd_tst\pqeditor.py", line 7, in <module>
    from pyqode.core import api
  File "D:/work/vex/pyqd_tst\pyqode\core\__init__.py", line 21, in <module>
    _('')
TypeError: 'str' object is not callable
```

**Comment by paulwinex** [comment]
Report of future installation
```
$ pip install future
Collecting future
c:\cg\houdini\15.5.480\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
c:\cg\houdini\15.5.480\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached future-0.15.2.tar.gz
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... error
  Complete output from command c:\cg\houdini\15.5.480\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mari\\appdata\\local\\temp\\pip-build-meev6v\\future\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\mari\appdata\local\temp\tmp44ley9pip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  >>>> Failed building wheel for future
  Running setup.py clean for future
Failed to build future
Installing collected packages: future
  Running setup.py install for future ... done
Successfully installed future-0.15.2
```

**Comment by ColinDuquesnoy** [comment]
> _('')
> TypeError: 'str' object is not callable

This error is not related to future. Have you defined ``_`` to a string previously? Maybe those issues are caused by the use of ``reload``? What if you restart the houdini process?

**Comment by paulwinex** [comment]
> What if you restart the houdini process?

Yes, it help us to move forward. Now Houdini is crash on show() function)))

**Comment by ColinDuquesnoy** [comment]
> Now Houdini is crash on show() function)))

Does it crash with a segmentation fault or do you have a traceback?

**Comment by paulwinex** [comment]
No, just close. I don't know why.

**Comment by paulwinex** [comment]
I record console output. It is last frame of Houdini
[http://prntscr.com/bfhtfi](http://prntscr.com/bfhtfi)

**Comment by ColinDuquesnoy** [comment]
Looks like you're creating the widget in another thread than the GUI thread. I don't know much about Houdini so I am afraid I cannot help much about this issue...

**Comment by paulwinex** [comment]
Yes. I thing it is problem in Houdini. Thanks. Maybe i will try to change sources.
