### ISSUE TITLE
qidle Missing

### ISSUE THREAD

**Issue by jmwright** [pyQode/pyQode#61]
I had been using the following code to embed packages for use with an app, but the repo for qidle seems to have been moved or removed.
```python
from qidle.system import embed_package_into_zip
    embed_package_into_zip([jedi, pep8, pyqode, pyqode.core, pyqode.python,
                            pyqode.qt, pygments, pyflakes, builtins, future, docutils, pint, pyparsing], ZIP)
```
Does this code still exist in some form somewhere?

**Comment by ColinDuquesnoy** [comment]
Nope, sorry. I've notified you that I would remove this repository. I've waited a few months before removing it.

But you can use this [script](https://github.com/HackEdit/hackedit/blob/master/scripts/update_vendor.py) to create a "vendor" directory, you would just have to create a zip archive from that directory...
