### ISSUE TITLE
[Unhandled exception] AttributeError

### ISSUE THREAD

**Issue by ColinDuquesnoy** [pyQode/pyQode#63]
_From @GitMensch on August 11, 2016 8:27_
### Description

Clicked whle pressing [CTRL]
### Traceback

```
  File "d:\documents\pyqode.cobol\pyqode\cobol\modes\goto.py", line 141, in _goto_def

AttributeError: 'NoneType' object has no attribute 'line'
```
### System information
- Operating System: Windows
- OpenCobolIDE: 4.7.4
- GnuCOBOL: cobc (GNU Cobol) 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.10.1
- pyqode.cobol: 2.10.1
- pyqode.qt: 2.10.0
- pygments: 2.0.2
- QDarkStyle: 2.1

Application log: https://gist.github.com/f4dffbd5e05d7d9453267e629df3fe84

_Copied from original issue: OpenCobolIDE/OpenCobolIDE#349_

**Comment by GitMensch** [comment]
Just a note:
This happened mostly when I just wanted to copy something but (at least today) also when a jump was the intention (and directly worked afterwards when repressing [CTRL], the word is underlined and blue as it was before and the [click] directly showed the section - which resulted in the exception before).

~~~~
13:49:56:958::CRITICAL::6980::open_cobol_ide.app::unhandled exception:
  File "d:\documents\pyqode.cobol\pyqode\cobol\modes\goto.py", line 141, in _goto_def

AttributeError: 'NoneType' object has no attribute 'line'
13:52:29:772::DEBUG::6980::pyqode.core.modes.autocomplete::next char: None
~~~~

(the second entry was after the working "jump" but this was only on loglevel DEBUG, I've switched to PYQODE_DEBUG for further investigation)

**Comment by GitMensch** [comment]
Happened again - If you need the log I can provide it but it is huge (and contains proprietary code).

BTW: most of the entries of PYQODE_DEBUG are heartbeat entries. Can I suggest to add a PYQODE_DEBUG_ALL and only include the heartbeat entries there?

**Comment by ColinDuquesnoy** [comment]
Thanks for the info. I think I have everything I need to fix this issue.
