### ISSUE TITLE
Syntax highlighting: free format sets all lines starting with * as comment lines

### ISSUE THREAD

**Issue by ColinDuquesnoy** [pyQode/pyQode#64]
_From @GitMensch on August 11, 2016 10:20_

Example:

``` cobol
        compute a = a
                  * b
                  / 20
```

Free format has only inline comments, these start with `*>`.
There are other formats like the ACU terminal format (where comments start in col 1 with an asterisk, debugging lines on col 1 with `D`, ...) but as GnuCOBOL doesn't support it (yet) we may don't need to support this in OCIDE.
Or add a checkbox "asterisk in column 1 as inline comment" (MF has a similar setting which GnuCOBOL supports) in Preferences... In any case this would only be about col 1.

_Copied from original issue: OpenCobolIDE/OpenCobolIDE#351_

**Comment by GitMensch** [comment]
Just to clarify:

``` cobolfree
compute a = a
* b
/ 20
```

the second line isn't a comment line. I'm not sure if this correctly implemented,

BTW: *really* nice to see that you're working on the next OCIDE version.
It is quite likely that GnuCOBOL 2.0 rc2 is available today, I may add an official MinGW package enabling you to package it with the next OCIDE version. What do you think about this?

**Comment by ColinDuquesnoy** [comment]
> the second line isn't a comment line. I'm not sure if this correctly implemented,

Ok, that's what you mean when you said "_add a checkbox "asterisk in column 1 as inline comment"_" . The current implementation have this option always ON. Since GnuCOBOL does not support it yet, I will just remove it.

**Comment by ColinDuquesnoy** [comment]
> It is quite likely that GnuCOBOL 2.0 rc2 is available today, I may add an official MinGW package enabling you to package it with the next OCIDE version. What do you think about this?

I plan to publish OCIDE 4.7.6 on Wednesday. If I can have GnuCOBOL 2.0-rc2 before Wednesday and if everything works well then it will be in that release.

**Comment by GitMensch** [comment]
GnuCOBOL supports this in fixed-form reference-format with `-fmfcomment` ;-) [the "you may add a checkbox for this" was referring this option]
The not-yet-supported terminal-form reference-format has this behaviour always, together with D in column 1 being a debugging line.

**Comment by ColinDuquesnoy** [comment]
This is a bit out of scope for this release. I will just adress the "Free format has only inline comments, these start with *>." issue. 

Feel free to open an issue in HackEdit for the ``-fmfcomment`` option and other things we should support in the future.

**Comment by GitMensch** [comment]
I don't like `-fmfcomment` and would everyone highly encourage to disable it (it is only in because of migration issues). Therefore I'm fine with not adding it for now (if anyone really likes to see it it can be added as feature request for HackEdit, until this happens it stays out and the code more clean).
