### ISSUE TITLE
Is there a waiting indicator available already?

### ISSUE THREAD

**Issue by GitMensch** [pyQode/pyQode#77]
The tree view in file system pane and other items may need some time to finish and the user does not always have a feedback.

If it doesn't exists would it be useful to place something like `wait_cursor` context manager shown in https://stackoverflow.com/a/35345399/5027456 to PyQode, maybe with something other than the hourglass (animation, possibly shown as an overlay over a PyQT object)?

**Comment by ColinDuquesnoy** [comment]
There is not such feature and I won't implement it. But I will accept a PR. 

You'd have to lookup for the [directoryLoaded](http://doc.qt.io/qt-4.8/qfilesystemmodel.html#directoryLoaded) signal to know when the gathered thread has finished loading the root directory and stop the hourglass animation.

> possibly shown as an overlay over a PyQT object

You can but pyqode does not provide such an overlay.
